name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt databricks-cli

      - name: Install dbt dependencies
        run: |
          dbt deps

      - name: Run dbt commands
        # Here you define environment variables for dbt and Databricks
        env:
          DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DBT_TARGET: prod
        run: |
          dbt run
          dbt test
