name: 'migration'
version: '1.0.0'

profile: 'migration'

model-paths: ["models/migration"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  migration:
    +schema: abhi
    bronze_table:
      materialized: table
      format: delta
    silver_table:
      materialized: table
      format: delta
    gold_table:
      materialized: table
      format: delta

